import numpy as np


def get_mask(I, nodata_value=-9999):
    """Generate masks for valid and invalid pixels. Some pixels could not be generated by 
    interpolation but are included because the image must be rectangular. These masks are
    useful to calculate statistics using only valid pixels.

    Args:
        I : Input interpolated image.
        nodata_value: Valued used to mark pixels with no valid data. Defaults to -9999.

    Returns:
        mask_valid: mask that marks valid pixels
        mask_invalid: mask that marks invalid pixels
    """


    mask_valid = I != nodata_value
    mask_invalid = I == nodata_value

    return mask_valid, mask_invalid

def get_residuals(true_values, predicted_values, mask_invalid=None):
    """Calculate image of resuduals by comparing reference values and calculated values. 
    Residual is set to 0 at invalid pixels to avoid these pixels from interfering with
    visualizations.

    Args:
        true_values: Reference data.
        predicted_values: Calculated values.
        mask_invalid: Mask of invalid pixels. Will be calculated with default values if not provided.

    Returns:
        Residuals. Note that the absolute values are not calculated to preserve the direction of the residual.
    """
    res = true_values - predicted_values
    if mask_invalid is not None:
        res[mask_invalid] = 0
    return res